### ISSUE TITLE
Iconscout.

### ISSUE THREAD

**Issue by champolot** [Kyutefox/Iconify#25] opened 2024-05-30 03:47 UTC
There is no preview on the icons and when downloaded. There is no icon displayed

**Comment by MrJukeman** [comment] 2024-05-30 06:30
@champolot Can you make it more clear about the issue

**Comment by champolot** [comment] 2024-05-30 13:21
It was on my end. Sorry for the confusion. I'll close this immediately

**Comment by champolot** [comment] 2024-05-31 08:32
I dont know if its really on my end. But maybe you could check it if you were able to have a preview of the icon. 
You could check this links:
https://iconscout.com/icon/notes-1462768
https://iconscout.com/icon/notes-1462768
I did use incognito and I was ablo have a preview of the icon. Could you please check it?

**Comment by MrJukeman** [comment] 2024-05-31 10:12
@champolot The issue seems to be there, I will have a look if its the issue from the extension or the site itself.

**Comment by champolot** [comment] 2024-05-31 12:36
Thanks for giving an attention on this matter. Cheers!

**Comment by MrJukeman** [comment] 2024-06-03 17:38
@champolot We tried to look into the issue, and the issue is not due to extension. The preview is unavailable when you are logged in and when you are not logged in the preview is there. We checked in multiple browsers and had a look into there console and found out that the issue is from their end.

**Closed** 2024-07-31 03:22 UTC
